### ISSUE TITLE
no implicit conversion from nil to integer

### ISSUE THREAD

**Issue by Jell** [jacott/Enhanced-Ruby-Mode#6]
ERM sometimes freezes, and I get the following in /tmp/erb.log:

```
"p16:1:991:835:0:}\n\u0000\u0000\u0000\n"
no implicit conversion from nil to integer
/Users/Jell/.emacs.d/el-get/Enhanced-Ruby-Mode/ruby/erm_buffer.rb:68:in `[]'
/Users/Jell/.emacs.d/el-get/Enhanced-Ruby-Mode/ruby/erm_buffer.rb:68:in `realadd'
/Users/Jell/.emacs.d/el-get/Enhanced-Ruby-Mode/ruby/erm_buffer.rb:30:in `nadd'
/Users/Jell/.emacs.d/el-get/Enhanced-Ruby-Mode/ruby/erm_buffer.rb:47:in `add'
/Users/Jell/.emacs.d/el-get/Enhanced-Ruby-Mode/ruby/erm_buffer.rb:332:in `on_rbrace'
/Users/Jell/.emacs.d/el-get/Enhanced-Ruby-Mode/ruby/erm_buffer.rb:423:in `parse'
/Users/Jell/.emacs.d/el-get/Enhanced-Ruby-Mode/ruby/erm_buffer.rb:423:in `block in parse'
/Users/Jell/.emacs.d/el-get/Enhanced-Ruby-Mode/ruby/erm_buffer.rb:422:in `catch'
/Users/Jell/.emacs.d/el-get/Enhanced-Ruby-Mode/ruby/erm_buffer.rb:422:in `parse'
/Users/Jell/.emacs.d/el-get/Enhanced-Ruby-Mode/ruby/erm_buffer.rb:528:in `parse'
/Users/Jell/.emacs.d/el-get/Enhanced-Ruby-Mode/ruby/erm.rb:45:in `block in <main>'
/Users/Jell/.emacs.d/el-get/Enhanced-Ruby-Mode/ruby/erm.rb:26:in `open'
/Users/Jell/.emacs.d/el-get/Enhanced-Ruby-Mode/ruby/erm.rb:26:in `<main>'
```

So I'm guessing that ErmBuffer does not know about the `p` command.

**Comment by jacott** [comment]
'p' is for "partial buffer change" and is what is normally sent when you type a character. It is not explicitly looked for in the parser as it is the default action.

The problem you encountered looks like unbalanced braces; '}' with no matching '{'.

I have commit a change to cater for this case.
